name = "kortteli-kauppa-stock-checker"
type = "webpack"
account_id = 'f6fb24cc834e70e7ba3b5285f4031e0f'
route = 'korttelikauppastockchecker.sillygoose.io/*'
zone_id = '356d3e98fa67af3d800b74d6beefe4c7'

[site]
bucket = "./build"
entry-point = "workers-site"