services:
  postgres_dev:
      container_name: pg_dev
      hostname: postgres
      image: postgres:13.3-alpine
      ports:
      - "5432:5432"
      environment:
        POSTGRES_USER: db_user
        POSTGRES_PASSWORD: d9383e87-c02f-4032-8b18-7515cbbe0b8f
        POSTGRES_DB: backend_dev
  postgres_test:
      container_name: pg_test
      hostname: postgres
      image: postgres:13.3-alpine
      ports:
      - "5433:5432"
      environment:
        POSTGRES_USER: db_user
        POSTGRES_PASSWORD: d9383e87-c02f-4032-8b18-7515cbbe0b8f
        POSTGRES_DB: backend_test
        